name: Docker-build
on: [push]
  branches: [main]
permissions:
  contents: read
  packages: write
  issues: write
jobs:
  Docker-build:
    name: Building Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: checking out the code
        uses: actions/checkout@v2
      - run: env
        name: checking env
      - run: ls -l

