name: Docker-build
on: 
  push:
    branches: [main]
permissions:
  contents: read
  packages: write
  issues: write
jobs:
  Docker-build:
    name: Building Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: checking out the code
        uses: actions/checkout@v3.6.0
      - name: checking env
        run: env
      - run: ls -l
      - name: Login to GitHub registry
        uses: docker/login-action@v2
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate image path
        run: |
          echo "Shamani"
          echo "Mohanty"
          echo "ghcr.io/${{github.repository}}:${GITHUB_SHA:0:7}"
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: Training/Docker1
          push: true
          tags: ghcr.io/shamani17/test1:latest